"use client";

import { FormEvent, useRef, useState } from "react";
import { API_BASE } from "../lib/api";
import { createClient } from "../lib/supabase/client";
import type { Source } from "../lib/types";

type Turn = { id: string; speaker: "family" | "echo"; text: string; sources?: Source[]; refusal?: boolean };

export function ConversationClient({ echoId }: { echoId: string }) {
  const [question, setQuestion] = useState("");
  const [turns, setTurns] = useState<Turn[]>([{ id: "welcome", speaker: "echo", text: "Hello, love. I am here to share only the stories I truly told. What would you like to ask me?" }]);
  const [sending, setSending] = useState(false);
  const recognition = useRef<{ start: () => void } | null>(null);

  const speak = (text: string) => {
    if ("speechSynthesis" in window) { window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(text)); }
  };
  const useVoice = () => {
    const SpeechRecognition = window.SpeechRecognition ?? window.webkitSpeechRecognition;
    if (!SpeechRecognition) { setQuestion("Voice input is not available in this browser. Please type your question."); return; }
    const instance = new SpeechRecognition();
    instance.onresult = (event: SpeechRecognitionEvent) => setQuestion(event.results[0][0].transcript);
    recognition.current = instance;
    instance.start();
  };
  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if (!question.trim() || sending) return;
    const asked = question.trim(); const responseId = `response-${Date.now()}`;
    setQuestion(""); setSending(true);
    setTurns((items) => [...items, { id: `question-${Date.now()}`, speaker: "family", text: asked }, { id: responseId, speaker: "echo", text: "" }]);
    try {
      const formData = new FormData();
      formData.append("text", asked);
      const { data: { session } } = await createClient().auth.getSession();
      if (!session) throw new Error("You must be signed in.");
      const response = await fetch(`${API_BASE}/echo/${encodeURIComponent(echoId)}/converse`, { method: "POST", headers: { "Authorization": `Bearer ${session.access_token}` }, body: formData });
      if (!response.body) throw new Error("The response stream did not start.");
      const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; let finalText = "";
      while (true) {
        const { done, value } = await reader.read(); if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const frames = buffer.split("\n\n"); buffer = frames.pop() ?? "";
        for (const frame of frames) {
          const dataLine = frame.match(/^data: (.+)$/m)?.[1]; if (!dataLine) continue;
          try {
            const data = JSON.parse(dataLine);
            if (data.type === "text") { finalText += data.text; setTurns((items) => items.map((turn) => turn.id === responseId ? { ...turn, text: finalText } : turn)); }
            if (data.type === "sources") setTurns((items) => items.map((turn) => turn.id === responseId ? { ...turn, sources: data.sources } : turn));
          } catch { /* skip malformed frames */ }
        }
      }
    } catch { setTurns((items) => items.map((turn) => turn.id === responseId ? { ...turn, text: "I am having trouble finding my memories right now. Please try again in a moment.", refusal: true } : turn)); }
    finally { setSending(false); }
  };
  return <section className="conversation-shell">
    <div className="conversation-copy"><p className="eyebrow">Your Echo</p><h1>Talk with a legacy</h1><p>Responses are generated by AI from verified memories, not original recordings.</p></div>
    <div className="conversation-grid"><div className="conversation-log" aria-live="polite">{turns.map((turn) => <article key={turn.id} className={`turn ${turn.speaker} ${turn.refusal ? "refusal" : ""}`}><span>{turn.speaker === "echo" ? "Echo" : "You"}</span><p>{turn.text || <i>Searching verified memories…</i>}</p>{turn.sources && <details><summary>Sources ({turn.sources.length})</summary>{turn.sources.map((source) => <div className="citation" key={source.memory_id}><b>{source.session_id}</b><p>{source.excerpt}</p></div>)}</details>}</article>)}</div>
      <aside className="voice-panel"><div className="wave"><i /><i /><i /><i /><i /></div><h2>Ask in your own words</h2><p>Speak or type a question.</p><form onSubmit={submit}><textarea value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="What do you remember about that time?" rows={4} /><div className="input-actions"><button type="button" className="secondary" onClick={useVoice}>Use voice</button><button type="submit" disabled={sending}>{sending ? "Remembering…" : "Ask Echo"}</button></div></form></aside>
    </div>
  </section>;
}

declare global {
  interface Window { SpeechRecognition?: new () => SpeechRecognition; webkitSpeechRecognition?: new () => SpeechRecognition; }
  interface SpeechRecognition extends EventTarget { start(): void; onresult: ((event: SpeechRecognitionEvent) => void) | null; }
  interface SpeechRecognitionEvent extends Event { results: { [index: number]: { [index: number]: { transcript: string } } }; }
}
