from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from .config import get_settings

from .routers import sessions, memories, echo, echo_conversation, finetune, auth, realtime, mind
from .db.client import db_client
from .auth.middleware import AuthMiddleware

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Initialize DB or external connections here
    await db_client.connect()
    yield
    # Clean up here
    await db_client.disconnect()

app = FastAPI(title="Echo API", version="0.1.0", lifespan=lifespan)
settings = get_settings()

app.add_middleware(GZipMiddleware, minimum_size=1000)
app.add_middleware(AuthMiddleware)

@app.get("/health")
def health() -> dict:
    return {
        "ok": True,
        "mode": "live",
        "missing_live_integrations": settings.missing_live_integrations,
    }

@app.get("/health/db")
async def health_db():
    if not db_client.pool:
        return {"ok": False, "status": "no pool initialized"}
    try:
        async with db_client.pool.acquire() as conn:
            await conn.execute("SELECT 1")
        return {"ok": True, "status": "connected"}
    except Exception as e:
        return {"ok": False, "status": str(e)}

@app.get("/health/redis")
def health_redis():
    if settings.development_mode:
        return {"ok": True, "status": "development mode, redis bypassed"}
    import redis
    import os
    try:
        r = redis.Redis.from_url(os.getenv("REDIS_URL", settings.redis_url))
        r.ping()
        return {"ok": True, "status": "connected"}
    except Exception as e:
        return {"ok": False, "status": str(e)}

@app.get("/health/providers")
def health_providers():
    """Reports provider configuration without disclosing credentials."""
    return {
        "ok": bool(settings.gemini_api_key and settings.groq_api_key),
        "gemini_live_model": settings.gemini_live_model,
        "groq_persona_model": settings.groq_persona_model,
    }

@app.get("/health/pinecone")
def health_pinecone():
    import os
    import httpx
    api_key = os.getenv("PINECONE_API_KEY", settings.pinecone_api_key)
    if not api_key:
        return {"ok": False, "status": "no api key"}
    return {"ok": True, "status": "pinecone api key configured"}

app.include_router(auth.router)
# Backward-compatible account deletion endpoint; the canonical endpoint is /auth/account.
app.add_api_route("/account", auth.delete_account, methods=["DELETE"], status_code=204)
app.include_router(sessions.router)
app.include_router(memories.router)
app.include_router(echo.router)
app.include_router(echo_conversation.router)
app.include_router(finetune.router)
app.include_router(realtime.router)
app.include_router(mind.router)

# Wrap the complete application rather than adding CORS inside the middleware
# stack.  This ensures CORS headers are also present on error responses
# generated by FastAPI/Starlette (including an unexpected database exception),
# so browsers surface the real HTTP error instead of a misleading failed fetch.
app = CORSMiddleware(
    app=app,
    allow_origins=[origin.strip() for origin in settings.cors_origins.split(",") if origin.strip()],
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type", "Accept", "Origin", "X-Requested-With"],
    max_age=600,
)
